name: OTPKitTests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# GitHub macOS Runner images are documented at:
# https://github.com/actions/runner-images?tab=readme-ov-file
# Installed versions of Xcode on macOS 15 are documented at:
# https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md

jobs:
  lint:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4

    - name: Install SwiftLint
      run: brew install swiftlint

    - name: Run SwiftLint
      run: swiftlint --strict

  build:
    runs-on: macos-15
    needs: lint

    steps:
    - uses: actions/checkout@v4

    - uses: actions/cache@v4
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Switch Xcode
      run: sudo xcode-select -switch /Applications/Xcode_26.2.app

    - name: List Available Simulators
      run: |
        xcrun simctl list devices

    # Build
    - name: Build OTPKit
      run: xcodebuild clean build-for-testing
        -scheme OTPKit
        -destination 'platform=iOS Simulator,name=iPhone 17 Pro'
        -quiet

    # Unit Test
    - name: OTPKit Unit Test
      run: xcodebuild test-without-building
        -scheme OTPKit
        -destination 'platform=iOS Simulator,name=iPhone 17 Pro'
        -resultBundlePath OTPKitTests.xcresult

    # Upload results
    - uses: kishikawakatsumi/xcresulttool@v1.7.0
      continue-on-error: true
      with:
        show-passed-tests: false    # Avoid truncation of annotations by GitHub by omitting succeeding tests.
        path: |
          OTPKitTests.xcresult
      if: success() || failure()
